version: "3"
services:

  database:
    container_name: database
    build:
      context: ./database
    environment:
      MYSQL_ROOT_PASSWORD: myrootpassword
      MYSQL_DATABASE: project
      MYSQL_USER: db_admin 
      MYSQL_PASSWORD: o]EsKiHd8W0WU2pc
    
    ports:
      - "3306:3306"

    networks:
      - mynetwork

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:4.9
    ports:
      - "8080:80"  # Port mapping format corrected   
    networks:
      - mynetwork
    environment:
      PMA_HOST: database  # Corrected PMA_HOST to match the service name
      PMA_USER: db_admin
      PMA_PASSWORD: o]EsKiHd8W0WU2pc

  node:
    container_name: node
    build:
      context: ./backend
    volumes:
      - ./backend:/app      
    networks:
      - mynetwork
    depends_on:
      - database

  nginx:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - mynetwork
    depends_on:
      - node

networks:
  mynetwork:  



volumes:
  mysql-data:

